---
- name: Create haproxy project dir
  file:
    path: "{{ project_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy static haproxy.cfg from Git
  copy:
    src: haproxy.cfg
    dest: "{{ project_dir }}/haproxy.cfg"
    owner: root
    group: root
    mode: '0644'
  notify: Restart haproxy via Docker Compose

- name: Template docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ project_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: '0644'

- name: Start / Update HAProxy
  community.docker.docker_compose_v2:
    project_src: "{{ project_dir }}"
    state: present
    build: always

